// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedPictureEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPictureEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202005132228328_addedPictureEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
